### ISSUE TITLE
HW3: Content blocks style mismatch

### ISSUE THREAD

**Issue by eko24ive** [x6iBeHbx/artinovWebProject#1]
Here is how your content blocks look like:
![image](https://cloud.githubusercontent.com/assets/25591824/23592165/7398af7c-0205-11e7-8dd2-d3eaa7e973ed.png)

Compare it to design:
![image](https://cloud.githubusercontent.com/assets/25591824/23592163/6b7fca78-0205-11e7-968c-b1bde7876868.png)

Please apply right width, padding, font color and size to them

**Comment by x6iBeHbx** [comment]
done

**Comment by eko24ive** [comment]
Great job !
