### ISSUE TITLE
HW3: Footer position

### ISSUE THREAD

**Issue by eko24ive** [x6iBeHbx/artinovWebProject#2]
Here is your footer:
![image](https://cloud.githubusercontent.com/assets/25591824/23592176/a11d94c6-0205-11e7-8660-20d3bdf3b931.png)

Compare it to design:
![image](https://cloud.githubusercontent.com/assets/25591824/23592178/a8e21e3e-0205-11e7-97e5-ddf3e9b27693.png)

As you can see - it is conflicting with content block.
Fix it's position, width and add horizontal line on top.

**Comment by x6iBeHbx** [comment]
done

**Comment by eko24ive** [comment]
Well done !
