### ISSUE TITLE
HW4: Content padding

### ISSUE THREAD

**Issue by eko24ive** [x6iBeHbx/artinovWebProject#3]
Compare your padding:
![image](https://cloud.githubusercontent.com/assets/25591824/23592219/3d1dc45e-0206-11e7-9ccc-540df042e91b.png)

To design:
![image](https://cloud.githubusercontent.com/assets/25591824/23592207/20c4c2f8-0206-11e7-9f3f-61bddab5c42b.png)

Please add required padding.

**Comment by x6iBeHbx** [comment]
done

**Comment by eko24ive** [comment]
Awesome !
