### ISSUE TITLE
HW4: Navigation mismatch

### ISSUE THREAD

**Issue by eko24ive** [x6iBeHbx/artinovWebProject#4]
Here is your navigation:
![image](https://cloud.githubusercontent.com/assets/25591824/23592237/61cf4c1e-0206-11e7-9dd2-475a33cf5c7c.png)

Lets compare it to design:
![image](https://cloud.githubusercontent.com/assets/25591824/23592232/59a196e6-0206-11e7-91b6-1770d66bcad8.png)

- Fix padding for it
- Align `Project` label
- Link hover effect must be with **inset** shadow
- Remove underline decoration for link
- All links must fit into one row

**Comment by x6iBeHbx** [comment]
done

**Comment by eko24ive** [comment]
Nicely done
