### ISSUE TITLE
HW4: Big block

### ISSUE THREAD

**Issue by eko24ive** [x6iBeHbx/artinovWebProject#5]
Here is your big container:
![image](https://cloud.githubusercontent.com/assets/25591824/23592251/a6796a0c-0206-11e7-9c30-9e1e7ce5830a.png)

Compare it to design:
![image](https://cloud.githubusercontent.com/assets/25591824/23592258/ae58865e-0206-11e7-9e82-a2b7799c9102.png)

Increase size of font, size and width of button

**Comment by x6iBeHbx** [comment]
done

**Comment by eko24ive** [comment]
Good job, keep it up !
