### ISSUE TITLE
HW4: Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [x6iBeHbx/artinovWebProject#6]
Compare your footer:
![image](https://cloud.githubusercontent.com/assets/25591824/23592264/cdb03dd0-0206-11e7-890e-d8c918d3e7e5.png)

To design:
![image](https://cloud.githubusercontent.com/assets/25591824/23592268/d57af51e-0206-11e7-86b8-9364909b0e43.png)

Footer must have additional padding, horizontal line on top and appropriate font styles

**Comment by x6iBeHbx** [comment]
done

**Comment by eko24ive** [comment]
Perfect
